export const data = {
    blogtitle1 : "The Webshop Protoype has been deployed",
    blog1 : "I have created a prototype of a webshop application, complete with both frontend and backend functionalities. The application is now available online for demonstration purposes. Its main features include the Landing Page, where users can browse and order products. Additionally, the Admin interface allows for various actions, such as listing orders, updating their status, adding new products, deactivating or deleting existing products, and modifying their components. The webshop prototype aims to provide a realistic shopping experience and showcase the functionalities and system I have developed. I have put a strong emphasis on intuitive user interface and seamless navigation, ensuring that customers can easily browse and place orders. This webshop prototype is the result of my efforts, and I am excited to share this project with the community. I hope that the demonstration of the application will be inspiring and engaging for those interested in web development and e-commerce. Stay tuned for more updates, as I will soon provide detailed demonstrations and share further projects!",
    date1:"2023.06.25.",
    blogtitle2 : "The Image Gallery App",
    blog2 :"I am thrilled to announce that I have created and released my own Image Gallery App. This new application allows you to upload, organize, display, and delete images. Here are some key features you will find in the app: The app enables you to easily and quickly upload your images. Sorting and Labeling: You can organize and label your images within the app, making it easy for visitors to navigate and discover your work. Visual Presentation: The app provides a visually appealing and user-friendly display for your images. I hope you will enjoy it. You can find the link to the gallery in the portfolio section.",
    date2:"2023.06.26.",
    blogtitle3 : "Downloadable CV",
    blog3 :"My CV is already done and ready for download. You can access and download it from the 'contacts' section.",
    date3:"2023.06.27.",
}